name: Commit database
on: push
jobs:
  database-commit:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: Create database and insert on table migrations
        run: |
          python sqlite_insert_executor.py

      - name: Verify migrations table
        run: |
          python sqlite_select_executor.py

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          git add migrations.db
          git commit -m "new migrations"
          git push origin master